# Site settings
baseURL = "https://mariecordes.netlify.app/"
languageCode = "en-us"
title = "Marie Cordes's Portfolio Website"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Marie Cordes"
  description = "Curious, enthusiastic and open-minded. Business & Management undergrad. Analytics & Management masters in 2021. Born and raised in Germany. Lived in Germany, the UK, Hong Kong & the US. Enjoy practicing yoga, making banana bread and wearing striped clothes. Food lover, world traveler and London explorer."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Marie Cordes's Portfolio Website"
    subtitle = ""
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "About me"
      url = "aboutme"
      
      [[params.navigation.links]]
      name = "All projects"
      url = "projects"

    #[[params.navigation.links]]
      #name = "Analysis - Brexit Voting"
      #url = "projects/brexitvoting"

     #[[params.navigation.links]]
      #name = "Analysis - IBM HR"
      #url = "projects/ibmhr"
      
      #[[params.navigation.links]]
      #name = "Analysis - Gapminder"
      #url = "projects/gapminder"
      
      #[[params.navigation.links]]
      #name = "Further Analyses"
      #url = "projects/furtherprojects"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
    name = "Download my CV"
    url = "docs/Marie_Cordes_CV_Nov2020.pdf"

    # Button Style 2
    #[[params.navigation.button2]]
      #name = "Log In"
      #url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Marie"
    subtitle = "This is my portfolio website full of information about me and the work I've done. Nice to meet you!"
    buttonText = "Get Started"
  


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "About me"
      subtitle = "Learn more about me"
      image = "pic01.jpg"
      url = "aboutme"

    [[params.tiles.showcase]]
      title = "CV"
      subtitle = "Learn more about my career path so far"
      image = "pic04.jpg"
      url = "docs/Marie_Cordes_CV_Nov2020.pdf"

[[params.tiles.showcase]]
      title = "BBC iPlayer - Cluster Analysis Report"
      subtitle = "Read the report on my cluster analysis of the BBC iPlayer's customer segments\n(Please find the code to the right)"
      image = "pic07.jpg"
      url = "docs/bbciplayer_clusteranalysis.pdf"

[[params.tiles.showcase]]
      title = "Cluster Analysis - BBC iPlayer"
      subtitle = "Learn more about my cluster analysis of the BBC iPlayer's customer segments using data mining techniques (Tools: k-means, k-medoid, hierarchical clustering, elobow analysis, silhouette analysis, PCA, dendograms)"
      image = "pic08.jpg"
      url = "projects/bbciplayer"
      
[[params.tiles.showcase]]
      title = "Linear regression & prediction - The Lending Club"
      subtitle = "Learn more about my linear regression analysis of the Lending Club's interest rates (Tools: Out-of-sample testing, Ordinary Least Squares, k-fold cross validation, learning curves, LASSO)"
      image = "pic09.jpg"
      url = "projects/lendingclub_linreg"
      
[[params.tiles.showcase]]
      title = "Logistic regression & classification - The Lending Club"
      subtitle = "Learn more about my logistic regression analysis of the Lending Club's default probabilities"
      image = "pic10.jpg"
      url = "projects/lendingclub_logreg"
      
[[params.tiles.showcase]]
      title = "Data Visualization Pt. 1 - London's Stop&Search"
      subtitle = "Learn more about data visualizations of the London Metropolitan Police's Stop&Search Service 09/2020"
      image = "pic04.jpg"
      url = "projects/stopandsearch1"
      
[[params.tiles.showcase]]
      title = "Data Visualization Pt. 2 - London's Stop&Search"
      subtitle = "Learn more about data visualizations of the London Metropolitan Police's Stop&Search Service 2017-2020"
      image = "pic11.jpg"
      url = "projects/stopandsearch2"
      
[[params.tiles.showcase]]
      title = "Worst Data Visualisation ever!"
      subtitle = "Look at my worst data visualisaton ever"
      image = "pic12.jpg"
      url = "projects/worstviz"
      
[[params.tiles.showcase]]
      title = "Consumer Survey Report - Heavenly Tea"
      subtitle = "Learn more about my consumer survey for Heavenly Tea's iced tea market entry"
      image = "pic13.jpg"
      url = "docs/heavenlytea.pdf"

    [[params.tiles.showcase]]
      title = "Brexit Voting Analysis"
      subtitle = "Learn more about my analysis of the 2016 Brexit referendum"
      image = "pic02.jpg"
      url = "projects/brexitvoting"
      
    [[params.tiles.showcase]]
      title = "IBM HR Analysis"
      subtitle = "Learn more about my analysis of the IBM HR dataset"
      image = "pic05.jpg"
      url = "projects/ibmhr"

    [[params.tiles.showcase]]
      title = "Gapminder Analysis"
      subtitle = "Learn more about my analysis of the gapminder dataset"
      image = "pic03.jpg"
      url = "projects/gapminder"

    [[params.tiles.showcase]]
      title = "Further Projects"
      subtitle = "Get a preview of some analyses I am currently working on"
      image = "pic06.jpg"
      url = "projects/furtherprojects"
      
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Learn more about who I am"
    subtitle = "Curious, enthusiastic and open-minded. Business & Management undergrad in 2019. Analytics & Management masters in 2021. Born and raised in Germany. Lived in the UK, Hong Kong & the US. Enjoy practicing yoga, making banana bread and wearing striped clothes. Food lover, world traveler and London explorer. Always up for a challenge. Looking to inspire and to be inspired."
    buttonText = "Take a look at my projects"
    url = "projects"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    formEmail = "mcordes.mam2021@london.edu"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "mcordes.mam2021@london.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "Available upon request"

    [[params.contact.address]]
    title = "Address"
    street = "London Business School, Regent's Park"
    city = "London, NW1 4SA"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Content and pictures by Marie Cordes "

    # Uses font awesome icons
    #[[params.footer.social]]
      #icon = "fa-twitter"
      #url= "https://www.twitter.com"
      #label = "Twitter"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/mariecordes/"
      label = "LinkedIn"
      
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/mariecordes"
      label = "GitHub"
      
    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/mariecordes6/"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/schokomarie/"
      label = "Instagram"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
